In [1]:
import torch
import numpy as np
import time

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [71]:
%%time
start_time = time.time()
#matrix operations here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00005674
CPU times: user 338 µs, sys: 128 µs, total: 466 µs
Wall time: 367 µs


In [70]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


0.00186110
0.14484549


In [76]:
#probability tensor
probabilities = torch.tensor([0.1, 0.9]) #10% of 0, 90% of 1
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [81]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [82]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [83]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [88]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [89]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [91]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [94]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

#stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [98]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
linear(sample)

tensor([ 4.4320, -6.8413,  0.9625], grad_fn=<SqueezeBackward4>)

In [99]:
import torch.nn.functional as F

#Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

#Apply softmax
softmax_output = F.softmax(tensor1, dim=0)

softmax_output


tensor([0.0900, 0.2447, 0.6652])

In [6]:
#Initialize an embedding layer
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

#Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

#Apply the embedding layer
embedded_output = embedding(input_indices)

embedded_output.shape


torch.Size([5, 100])

In [8]:
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
a @ b

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [93]:
int_64 = torch.randint(1, (2,3)).float()
float_32 = torch.rand(2,3)
int_64
#float_32

tensor([[0., 0., 0.],
        [0., 0., 0.]])